# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-17 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u0430')),
            ],
            options={
                'db_table': '\u041d\u043e\u043c\u0435\u0440\u0430 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u043e\u0432',
                'verbose_name': '\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u0430',
                'verbose_name_plural': '\u041d\u043e\u043c\u0435\u0440\u0430 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stop', models.CharField(max_length=500, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438')),
            ],
            options={
                'db_table': '\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a',
                'verbose_name': '\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438',
                'verbose_name_plural': '\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043e\u043a',
            },
        ),
        migrations.CreateModel(
            name='TimeForBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=500, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BUS', to='TableStopApp.BusNumber', verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u0430')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STOP', to='TableStopApp.BusStop', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438')),
            ],
            options={
                'db_table': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f',
                'verbose_name': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f',
                'verbose_name_plural': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f',
            },
        ),
    ]
