# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_bus', models.IntegerField()),
                ('stop_1', models.CharField(blank=True, max_length=500)),
                ('stop_2', models.CharField(blank=True, max_length=500)),
                ('stop_3', models.CharField(blank=True, max_length=500)),
                ('stop_4', models.CharField(blank=True, max_length=500)),
                ('number', models.CharField(choices=[['0', '']], default='curs', max_length=1)),
            ],
        ),
    ]
