# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableStopApp', '0002_auto_20180607_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeforbus',
            name='stops',
        ),
    ]
