# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TableStopApp', '0005_auto_20180609_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeforbus',
            options={'verbose_name': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f', 'verbose_name_plural': '\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u0438\u0431\u044b\u0442\u0438\u044f'},
        ),
    ]
