# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TableStopApp', '0006_auto_20180609_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busnumber',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='name_stop',
            field=models.CharField(max_length=500, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='timeforbus',
            name='time',
            field=models.CharField(max_length=500, verbose_name='\u0412\u0440\u0435\u043c\u044f'),
        ),
    ]
