# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TableStopApp', '0007_auto_20180609_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeforbus',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusNumber', to='TableStopApp.BusNumber'),
        ),
        migrations.AlterField(
            model_name='timeforbus',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BusStop', to='TableStopApp.BusStop'),
        ),
    ]
