# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TableStopApp', '0008_auto_20180609_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeforbus',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BUS', to='TableStopApp.BusNumber', verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u0431\u0443\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='timeforbus',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='STOP', to='TableStopApp.BusStop', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438'),
        ),
    ]
